CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Frauds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ImpostorDetails" text NOT NULL,
    "ContactInfo" text NOT NULL,
    "Comments" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Frauds" PRIMARY KEY ("Id")
);

CREATE TABLE "Libraries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Location" text NOT NULL,
    CONSTRAINT "PK_Libraries" PRIMARY KEY ("Id")
);

CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "LibraryId" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Books_Libraries_LibraryId" FOREIGN KEY ("LibraryId") REFERENCES "Libraries" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Books_LibraryId" ON "Books" ("LibraryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260612034941_CreateFraudsTable', '6.0.0');

COMMIT;

