-- Supabase SQL Editor: create only the fraud reports table.
-- Matches the Entity Framework migration for the Fraud entity.

CREATE TABLE IF NOT EXISTS "Frauds" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ImpostorDetails" text NOT NULL,
    "ContactInfo" text NOT NULL,
    "Comments" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Frauds" PRIMARY KEY ("Id")
);
